### Taken from https://wiki.archlinux.org/title/Toolbox
FROM docker.io/archlinux/archlinux:latest

ENV NAME=arch-toolbox VERSION=rolling

LABEL com.github.containers.toolbox="true" \
  name="$NAME" \
  version="$VERSION"

RUN pacman -Syu --noconfirm \
  && pacman -S sudo --noconfirm \
  && pacman -Scc --noconfirm \
  && echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox

CMD ["bash"]
###

# Install base packages
RUN pacman -S --noconfirm \
  base-devel curl openssh git bash-completion \
  podman \
  aws-cli-v2 \
  fzf ripgrep neovim wl-clipboard \
  python-pip python-virtualenv python-pipx \
  nodejs npm \
  neofetch \
  && echo "EDITOR=nvim" >> /etc/environment

# Install python tooling
ENV PIPX_HOME=/opt/pipx
ENV PIPX_BIN_DIR=/usr/local/bin
RUN pipx install pylsp-mypy --include-deps \
  && pipx install black --include-deps \
  && pipx install isort --include-deps \
  && pipx install awsume --include-deps \
  && pipx install poetry --include-deps

# Install nodejs tooling
RUN npm i -g eslint_d typescript typescript-language-server vscode-langservers-extracted

# Install asdf
ENV ASDF_DATA_DIR=/opt/asdf
## cpio is the only makedep from asdf
RUN pacman -S --noconfirm cpio \
  && sudo -u nobody git clone https://aur.archlinux.org/asdf-vm.git /tmp/asdf-vm \
  && cd /tmp/asdf-vm \
  && sudo -u nobody makepkg \
  && pacman -U --noconfirm asdf-vm-*.pkg.tar.zst \
  && mkdir -p $ASDF_DATA_DIR \
  && chgrp -R wheel $ASDF_DATA_DIR \
  && echo "ASDF_DATA_DIR=$ASDF_DATA_DIR" >> /etc/environment \
  && echo ". /opt/asdf-vm/asdf.sh" >> /etc/profile \
  && rm -rf /tmp/asdf-vm

# Install asdf-nodejs
RUN source /etc/profile \
  && asdf plugin add nodejs \
  && asdf install nodejs 18.12.1 \
  && asdf plugin add python \
  && asdf install python 3.9.16 \
  && chgrp -R wheel $ASDF_DATA_DIR \
  && chmod -R 775 $ASDF_DATA_DIR

# Install grpcurl
RUN sudo -u nobody git clone https://aur.archlinux.org/grpcurl-bin.git /tmp/grpcurl-bin \
  && cd /tmp/grpcurl-bin \
  && sudo -u nobody makepkg \
  && pacman -U --noconfirm grpcurl-bin-*.pkg.tar.zst
