### Taken from https://wiki.archlinux.org/title/Toolbox
FROM docker.io/archlinux/archlinux:latest

ENV NAME=arch-toolbox VERSION=rolling

LABEL com.github.containers.toolbox="true" \
  name="$NAME" \
  version="$VERSION"

# Set locale
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
  && locale-gen \
  && echo "LANG=en_US.UTF-8" > /etc/locale.conf

RUN pacman -Syu --noconfirm \
  && pacman -S sudo --noconfirm \
  && pacman -Scc --noconfirm \
  && echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox

CMD ["bash"]
###

# Install base packages
RUN pacman -S --noconfirm \
  base-devel curl openssh git bash-completion zip unzip bc \
  libvirt vagrant podman aws-cli-v2 terraform \
  fzf ripgrep neovim wl-clipboard \
  python-pip python-virtualenv python-pipx \
  neofetch \
  && echo "EDITOR=nvim" >> /etc/environment

# Install python tooling
ENV PIPX_HOME=/opt/pipx
ENV PIPX_BIN_DIR=/usr/local/bin
RUN pipx install pylsp-mypy --include-deps \
  && pipx install poetry --include-deps \
  && pipx install black --include-deps \
  && pipx install isort --include-deps \
  && pipx install pylint --include-deps

# Terraform utils
RUN sudo -u nobody git clone https://aur.archlinux.org/terraform-ls-bin.git /tmp/terraform-ls-bin \
  && cd /tmp/terraform-ls-bin \
  && sudo -u nobody makepkg \
  && pacman -U --noconfirm terraform-ls-bin-*.pkg.tar.zst
